CREATE TABLE PARTICIPANT (
  UUID             CHAR(36) PRIMARY KEY,
  CREATED          TIMESTAMP   NOT NULL,
  UPDATED          TIMESTAMP   NOT NULL,
  FIRST_NAME       VARCHAR(80) NOT NULL,
  LAST_NAME        VARCHAR(80) NOT NULL,
  ADDITIONAL_NAMES VARCHAR(80) NOT NULL
);

CREATE TABLE ADDRESS (
  UUID             CHAR(36) PRIMARY KEY,
  CREATED          TIMESTAMP   NOT NULL,
  UPDATED          TIMESTAMP   NOT NULL,
  STREET_ADDRESS   VARCHAR(80) NOT NULL,
  POSTAL_CODE      VARCHAR(10) NOT NULL,
  CITY             VARCHAR(80) NOT NULL,
  PARTICIPANT_UUID CHAR(36)    NOT NULL,
  FOREIGN KEY (PARTICIPANT_UUID)
  REFERENCES PARTICIPANT (UUID)
);

--INSERT INTO PARTICIPANT (uuid, created, updated, first_name, last_name, additional_names) VALUES (?,?,?,?,?,?)